### ISSUE TITLE
Issue with LLava when trying to import generators

### ISSUE THREAD

**Issue by Lord-Psarris** [IntelLabs/fastRAG#64]
I keep getting an error with the Llava import when trying to import anything from FastRAG. I first noticed it when trying to setup fastrag for a project. It occurs when importing rankers, generators and most features I've tested

Details:
- Python version = Python 3.8.10
- FastRAG version = fastrag-3.0.2
- Code Sample:
```python
from fastrag.rankers import IPEXBiEncoderSimilarityRanker
```

- Error:
```python
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from fastrag.rankers import IPEXBiEncoderSimilarityRanker
  File "/home/emmanuel/MARKETPLACE/.venv/lib/python3.8/site-packages/fastrag/__init__.py", line 2, in <module>
    from fastrag import generators, rankers, retrievers, stores
  File "/home/emmanuel/MARKETPLACE/.venv/lib/python3.8/site-packages/fastrag/generators/__init__.py", line 4, in <module>
    from .llava import LlavaHFGenerator
  File "/home/emmanuel/MARKETPLACE/.venv/lib/python3.8/site-packages/fastrag/generators/llava.py", line 24, in <module>
    class LlavaHFGenerator(HuggingFaceLocalGenerator):
  File "/home/emmanuel/MARKETPLACE/.venv/lib/python3.8/site-packages/fastrag/generators/llava.py", line 115, in LlavaHFGenerator
    images: list[str] = None,
TypeError: 'type' object is not subscriptable
```

**Comment by danielfleischer** [comment]
Update from master and try it out now.

**Comment by Lord-Psarris** [comment]
Issue resolved. Thank you
